### ISSUE TITLE
Updater doesn't work anymore after V2.7.0 update

### ISSUE THREAD

**Issue by QuailStudio** [mattpannella/pocket-updater-utility#56] opened 2022-11-13 07:38 UTC
<img width="365" alt="Screenshot 2022-11-13 at 3 37 21 PM" src="https://user-images.githubusercontent.com/16866181/201511227-5d8aa65a-6172-45df-bfd7-3b23447e528e.png">

**Comment by mattpannella** [comment] 2022-11-14 00:25
have you tried again, I'm unable to reproduce this but it looks like it may have been a network issue communicating with github

**Comment by QuailStudio** [comment] 2022-11-14 17:05
I just tried again I get the same  thing

**Comment by mattpannella** [comment] 2022-11-17 00:35
os and version?

**Comment by QuailStudio** [comment] 2022-11-17 05:24
MacOS Ventura 13.0 (22A380)
Analogue pocket 1.1-beta-6

**Comment by mattpannella** [comment] 2022-11-27 18:28
i haven't been able to reproduce this, i'm not really sure whats going on
it's something network related, but not really sure what

**Comment by Tolaris** [comment] 2022-12-06 10:15
I'm just here to help, by keeping the bug list under control. Shall we close this as not reproduce-able?

**Comment by mattpannella** [comment] 2022-12-06 16:56
yeah i think so. @QuailStudio has this issue persisted into 2.8.x for you?

**Comment by mattpannella** [comment] 2022-12-07 04:17
i feel like this is probably a network timeout, but i dont know why it would only happen to you (that i know of)
can you hit this address in a browser? https://joshcampbell191.github.io/openfpga-cores-inventory/api/v1/analogue-pocket/cores.json
its just trying to grab that file

**Comment by QuailStudio** [comment] 2022-12-07 05:03
I have no issue seeing this json in my browser

**Comment by cccharle** [comment] 2022-12-13 03:15
FWIW, I encountered a similar issue when attempting to run 2.9.4 from behind a VPN. I was able to access (https://joshcampbell191.github.io/openfpga-cores-inventory/api/v1/analogue-pocket/cores.json) via https in-browser, but hit a timeout when attempting to run the updater itself.

After disabling my VPN, the updater connected as expected. After re-enabling the VPN, the timeouts returned. YMMV.

**Comment by daveblood** [comment] 2023-02-07 15:10
hello,
     Probably a dumb question but the updater sort of stopped working.  When I click the exe file it updates most things but then a bunch of lines that say "unable to find prom in archive" im not sure what that means.  The updater has been working great for me up until now. im using 2.10.3.  Sorry im very new at this sort of thing

**Comment by mattpannella** [comment] 2023-02-07 15:16
download the newest release

**Comment by daveblood** [comment] 2023-02-07 15:23
Thank you Matt.  I'm sort of figuring this out as I go.  I originally thought that launching that exe file would update the updater.  I didnt realize I had to download a new file.  I downloaded and replaced the existing exe on the sd card and it worked.  Thank you.  Love this updater!

**Comment by mattpannella** [comment] 2023-02-07 15:55
yeah there was a bug in versions before 2.11 that didnt properly check for updates. it should prompt you from now on

**Closed** 2023-02-07 15:55 UTC
