### ISSUE TITLE
CPS1 Assets Fail to Install, Tested on Mac

### ISSUE THREAD

**Issue by jasonridesabike** [mattpannella/pocket-updater-utility#94] opened 2022-12-30 23:36 UTC
Thanks for the awesome util!

Ran into this issue running MacOS latest and having tested on no other devices. CPS1 assets are failing to install:

> Checking Core: jotego.jtcps1
> No releases found. Skipping
> Looking for Assets
> Already installed: chikij.rom
> Uh oh something went wrong.
> '0x00' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.

**Comment by mattpannella** [comment] 2022-12-31 13:00
hm
does it always check chikij.rom and then fail right after every time?

**Comment by mattpannella** [comment] 2022-12-31 14:02
can you paste the contents of your `Carrier Air Wing (World 901009).json` file in here?

**Comment by mrkenyatta** [comment] 2023-01-02 01:48
{
	"instance":{
		"magic": "APF_VER_1",
		"variant_select": {
			"id": 0,
			"select": false
		},
		"data_path": "",
		"data_slots": [
			{
				"id": 1,
				"filename": "cawingr1.rom"
			}
		],
		"memory_writes": [
			{
				"address": "0xf9000000",
				"data": "0x0"
			},
			{
				"address": "0xfa000000",
				"data": "0xfffc9f"
			}
		]
	}
}

**Comment by mattpannella** [comment] 2023-01-02 03:10
i'm kind of stuck right now, no idea why this is happening for a few people. i just posted a 2.10.1 update that should help a little bit. it won't break if there's an error, it will just move on to the next rom and try again

**Comment by mattpannella** [comment] 2023-01-02 15:02
ok the issue is the hidden dot files macos puts on external volumes. the 2.10.1 should work right now, it will just show all the failed attempts at reading the hidden files. i'll get another update out soon that doesnt try reading them in the first place

**Comment by mattpannella** [comment] 2023-01-02 23:20
this should be fixed in 2.10.2 via #96

**Closed by mattpannella** 2023-01-02 23:20 UTC

**Comment by jasonridesabike** [comment] 2023-01-03 15:59
Just chiming in to report this issue as fixed for me. Thanks!
